# for mac arm chips see:
# - https://docs.docker.com/desktop/troubleshoot/known-issues/

# for nvidia gpus see:
# - https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/Makefile
# - https://github.com/NVIDIA/nvidia-container-toolkit?tab=readme-ov-file
# - https://docs.docker.com/compose/gpu-support/

services:
  main:
    container_name: main
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    ports:
      - '8888:8888'
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/amd64 ubuntu:20.04

        ARG DEBIAN_FRONTEND=noninteractive
        
        RUN apt-get update && apt-get install -y git python3 python3-pip
        RUN pip3 install --upgrade pip && pip3 install numpy pandas torch torchvision torchaudio 

        # jupyter server via http://localhost:8888/lab
        # RUN pip install jupyter jupyterlab jupyter_contrib_nbextensions
        # ENV JUPYTER_ENABLE_LAB=yes
        # EXPOSE 8888
        # CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser", "--ServerApp.token=''", "--ServerApp.password=''", "--ServerApp.allow_origin='*'", "--ServerApp.disable_check_xsrf=True", "--ServerApp.allow_root=True", "--ServerApp.open_browser=False"]

        CMD ["tail", "-f", "/dev/null"]
